# Generated by Django 3.2.25 on 2026-05-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resume_ia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
